### ISSUE TITLE
Drop Plan Rendering Broken by Most Recent PR?

### ISSUE THREAD

**Issue by gerrylowe** [yanivsegev/VSTS-DropPlan#102] opened 2024-01-16 15:23 UTC
Sometime in the last few hours, Drop Plan has stopped rendering.  The following error is presented (tested on both Chrome & Edge):
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/10186807/418865e2-0207-44d0-a5b9-b2f129770c01)

**Comment by sgtwilko** [comment] 2024-01-16 15:25
Sorry, yes, I think I've fixed that in pr #101

**Comment by sgtwilko** [comment] 2024-01-16 15:31
@gerrylowe what's your project process? Agile, etc?
Do your tasks have parents?

**Comment by gerrylowe** [comment] 2024-01-16 15:38
1. Project process is Agile
2. Tasks have parents (e.g. Stories or Bugs)

If it helps, here's my browser console output:
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/10186807/cfe74bce-3a26-493b-a258-379f3a6ef1d8)

**Comment by sgtwilko** [comment] 2024-01-16 16:08
are the parents in the same iteration?

**Comment by lucasllano** [comment] 2024-01-16 16:09
Same problem here: 

https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/yanivsegev/Drop-plan-extension/Data/Scopes/Default/Current/Collections/Settings/Documents/version%201

![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/eb50bc09-0f4a-4c9e-97b1-86a718207942)
![image](https://github.com/yanivsegev/VSTS-DropPlan/assets/4128419/69d81220-0352-42ff-ac69-8c4502a6b79d)

**Comment by kamimorgan** [comment] 2024-01-16 16:14
We are also receiving the same error for most of our projects, it seems that this has started happening in last few hours today

**Comment by richard-fairweather-access** [comment] 2024-01-16 16:22
I have found that this is caused by
- tasks in a different sprint iteration from their parent
- predecessor/successor links that cross sprint iterations

I have been able to work around by updating iterations and removing links to avoid the above scenarios, but would prefer to be able to use the drop plan as before.

**Comment by sgtwilko** [comment] 2024-01-16 16:31
@richard-fairweather-access  I believe both of these are fixed in my new pr #101

**Comment by gerrylowe** [comment] 2024-01-16 16:46
> are the parents in the same iteration?

@sgtwilko Not always!

**Comment by yanivsegev** [comment] 2024-01-16 17:39
Uploaded a fix, Thanks @sgtwilko !

**Comment by sgtwilko** [comment] 2024-01-16 17:50
@yanivsegev  thanks for merging so quickly.

@richard-fairweather-access  thanks for working out the combinations in your environment, it confirmed what I'd suspected.

Hopefully that's sorted the issues for everyone, but if it hasn't can you tag me in any new issues you open.

**Comment by yanivsegev** [comment] 2024-01-16 17:56
@sgtwilko Thanks for all of your efforts!
Would you like to get access to TrackJs monitoring tool? if so, please share your email and I will send you an invite.

**Comment by sgtwilko** [comment] 2024-01-16 19:50
@gparreira do you see the same if you change the Theme to "Classic"?
Are they a different type of task?

**Comment by gparreira** [comment] 2024-01-16 19:52
Yes, it shows the sama format if I change the theme. The tasks were displaying normally some hours ago but after the error stopped it stays like that

**Comment by sgtwilko** [comment] 2024-01-16 20:03
@gparreira  ok, I think I understand the issue.
Do you manage bugs with tasks?

**Comment by sgtwilko** [comment] 2024-01-16 20:23
@gparreira I think PR #104 will fix your issue.

**Comment by gparreira** [comment] 2024-01-16 20:38
> @gparreira ok, I think I understand the issue. Do you manage bugs with tasks?

In fact we use to have bugs in the board but I don't know if there is one showed in this sprint.

> @gparreira I think PR #104 will fix your issue.

Yes, really!! Board is back to normal. Thank you very much!!!

**Closed** 2024-01-17 18:29 UTC
