### ISSUE TITLE
Drop Plan Bug

### ISSUE THREAD

**Issue by StanFadeyev** [yanivsegev/VSTS-DropPlan#34] opened 2018-05-17 09:39 UTC
Hi Yaniv!
Drop Plan is not worked in VSTS. Could you help me? 
It's all what I see on a Drop Plan screen. 
![67e647ed52c50d9a00d83a5472cbf5b2](https://user-images.githubusercontent.com/39367698/40165358-7530e24c-59c4-11e8-9e4d-1dc541462f0e.png)

Browser Console:
![1446266e21c86610f884d1bb793e539a](https://user-images.githubusercontent.com/39367698/40171820-260c06e0-59d5-11e8-94c2-76504f1feb9a.png)

But in second project I see this:
![096f51ab81efa24e9b79f6f043bb2732](https://user-images.githubusercontent.com/39367698/40165359-7555f91a-59c4-11e8-96e3-43532cb508e4.png)

Best regards, 
Stan

**Comment by nschonni** [comment] 2018-05-17 15:50
Duplicate of #33

**Comment by rsheynin** [comment] 2018-05-22 07:26
[
![dropplanusersbugscapture](https://user-images.githubusercontent.com/4847580/40347881-8d21d746-5daa-11e8-9802-b1720da3fef4.PNG)
](url)

**Comment by yanivsegev** [comment] 2018-07-01 01:46
Issue fixed, thanks to @MarkGaze 
Can you please confirm it is working now?

**Closed by yanivsegev** 2018-07-01 01:46 UTC
